[package]
name = "instachunk"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Near-infinite procedural worlds"
readme = "README.md"
repository = "https://github.com/cubkit/instachunk"
categories = ["game-development"]
exclude = ["out/", ".*", "*.code-workspace"]

[dependencies]
rand = "0.10.1"
rand_seeder = "0.5.0"
opensimplex_noise_rs = "0.3.0"

[dev-dependencies]
image = "0.25.10"